import 'package:flutter_test/flutter_test.dart';
import 'package:woolies_scanner/core/models/product_model.dart';

void main() {
  group('Product', () {
    test('toMap() returns correct map without id', () {
      final product = Product(
        name: 'Test Product',
        brand: 'Test Brand',
        barcode: '123456',
        aisle: 'OGE001',
        planogramDate: '10/04/2025',
        sheetName: 'OGE',
        quantity: 2,
      );

      final map = product.toMap();

      expect(map['name'], 'Test Product');
      expect(map['brand'], 'Test Brand');
      expect(map['barcode'], '123456');
      expect(map['aisle'], 'OGE001');
      expect(map['planogram_date'], '10/04/2025');
      expect(map['sheet_name'], 'OGE');
      expect(map['quantity'], 2);
      expect(map['estimated_price'], 0.0);
      expect(map['category'], 'General');
      // id should NOT be in toMap (auto-generated by PostgreSQL)
      expect(map.containsKey('id'), false);
    });

    test('fromMap() parses Supabase row correctly', () {
      final map = {
        'id': 42,
        'name': 'Woolworths Milk 2L',
        'brand': 'Woolworths',
        'barcode': '9300633555032',
        'aisle': 'FGE003',
        'planogram_date': '10/04/2025',
        'sheet_name': 'FGE',
        'quantity': 1,
        'estimated_price': 3.50,
        'category': 'Dairy',
        'scanned_at': '2025-04-10T10:00:00.000Z',
      };

      final product = Product.fromMap(map);

      expect(product.id, '42');
      expect(product.name, 'Woolworths Milk 2L');
      expect(product.barcode, '9300633555032');
      expect(product.aisle, 'FGE003');
      expect(product.planogramDate, '10/04/2025');
      expect(product.sheetName, 'FGE');
      expect(product.estimatedPrice, 3.50);
      expect(product.category, 'Dairy');
    });

    test('fromMap() handles null/missing fields gracefully', () {
      final map = <String, dynamic>{};

      final product = Product.fromMap(map);

      expect(product.name, 'Unknown');
      expect(product.barcode, null);
      expect(product.aisle, null);
      expect(product.planogramDate, null);
      expect(product.estimatedPrice, 0.0);
      expect(product.category, 'General');
      expect(product.quantity, 1);
    });

    test('toJson() and fromJson() round-trip correctly', () {
      final original = Product(
        name: 'Test Product',
        brand: 'Brand',
        barcode: '9300633555032',
        aisle: 'OGE005',
        planogramDate: '10/04/2025',
        sheetName: 'OGE',
        estimatedPrice: 5.99,
        category: 'Grocery',
        quantity: 3,
        scanDate: DateTime(2025, 4, 10, 10, 0, 0),
      );

      final json = original.toJson();
      final restored = Product.fromJson(json);

      expect(restored.name, original.name);
      expect(restored.barcode, original.barcode);
      expect(restored.aisle, original.aisle);
      expect(restored.planogramDate, original.planogramDate);
      expect(restored.sheetName, original.sheetName);
      expect(restored.estimatedPrice, original.estimatedPrice);
      expect(restored.category, original.category);
      expect(restored.quantity, original.quantity);
    });

    test('fromMap() converts bigint id to string', () {
      final map = {'id': 99, 'name': 'Item'};
      final product = Product.fromMap(map);
      expect(product.id, '99');
    });
  });
}
